name: build-36.04

on:
  push:
    branches: [ "36.04", "master" ]
  pull_request:
    branches: [ "36.04" ]
  workflow_dispatch:

jobs:
  linux64:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        model: [128K, 512Ke, Plus, SE, Classic, SEFDHD, II]
        depth: [0,5]
        exclude:
          - model: 128k
            depth: 5
          - model: 512Ke
            depth: 5 
          - model: Plus
            depth: 5
          - model: SE
            depth: 5 
          - model: Classic
            depth: 5 
          - model: SEFDHD
            depth: 5 
          - model: II
            depth: 0
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: 36.04
     #- name: install required packages 
       # run: sudo apt install mingw-w64 gcc-mingw-w64-i686 clang
      - name: Cache Build Tool
        id: cache-build-linux-tool64
        uses: actions/cache@v3
        with:
          path: setup_t
          key: ${{ runner.os }}-setup_t-linux64
      - name: build setup tool
        if: steps.cache-build-linux-tool64.outputs.cache-hit != 'true'
        run: gcc setup/tool.c -o setup_t
      - name: configure dev options
        run: |
           mkdir -p downloads
           echo "#define kMaintainerName \"Jake Thomas\"" > setup/CONFIGUR.i
           echo "#define kStrHomePage \"https://github.com/jake01756/Mini-vMac\"" >> setup/CONFIGUR.i
           echo "#define cur_ide gbk_ide_mgw" >> setup/CONFIGUR.i
      - name: build linux x64 mPlus
        run: |
           ./setup_t -t lx64 -n "minivmac-36.04-lx64-m${{ matrix.model }}-512x484" -m ${{ matrix.model }} -hres 512 -vres 384 -depth ${{ matrix.depth }} -sound 1 -drives 12 > setup.sh
           . setup.sh && make
           mv minivmac minivmac-36.04-lx64-${{ matrix.model }}-512x384
           #./setup_t -t lx64 -n "minivmac-36.04-lx64-m${{ matrix.model }}-512x384" -maintainer "Jake Thomas" -homepage "github.com/jake01756/Mini-vMac" -m ${{ matrix.model }} -depth ${{ matrix.depth }} -hres 512 -vres 384 -sound 1 -drives 12 > setup.sh

           ./setup_t -t lx64 -n "minivmac-36.04-lx64-m${{ matrix.model }}-640x400" -m ${{ matrix.model }} -hres 640 -vres 400 -depth ${{ matrix.depth }} -sound 1 -drives 12 > setup.sh
           . setup.sh && make
           mv minivmac minivmac-36.04-lx64-${{ matrix.model }}-640x400
          
           ./setup_t -t lx64 -n "minivmac-36.04-lx64-m${{ matrix.model }}-640x512" -m ${{ matrix.model }} -hres 640 -vres 512 -depth ${{ matrix.depth }} -sound 1 -drives 12 > setup.sh
           . setup.sh && make
           mv minivmac minivmac-36.04-lx64-${{ matrix.model }}-640x512
           
           ./setup_t -t lx64 -n "minivmac-36.04-lx64-m${{ matrix.model }}-704x450" -m ${{ matrix.model }} -hres 704 -vres 450 -depth ${{ matrix.depth }} -sound 1 -drives 12 > setup.sh
           . setup.sh && make
           mv minivmac minivmac-36.04-lx64-${{ matrix.model }}-704x450
           
           ./setup_t -t lx64 -n "minivmac-36.04-lx64-m${{ matrix.model }}-832x525" -m ${{ matrix.model }} -hres 832 -vres 525 -depth ${{ matrix.depth }} -sound 1 -drives 12 > setup.sh
           . setup.sh && make
           mv minivmac minivmac-36.04-lx64-${{ matrix.model }}-832x525
           
           ./setup_t -t lx64 -n "minivmac-36.04-lx64-m${{ matrix.model }}-960x540" -m ${{ matrix.model }} -hres 960 -vres 540 -depth ${{ matrix.depth }} -sound 1 -drives 12 > setup.sh
           . setup.sh && make
           mv minivmac minivmac-36.04-lx64-${{ matrix.model }}-960x540
           
           ./setup_t -t lx64 -n "minivmac-36.04-lx64-m${{ matrix.model }}-960x600" -m ${{ matrix.model }} -hres 960 -vres 600 -depth ${{ matrix.depth }} -sound 1 -drives 12 > setup.sh
           . setup.sh && make
           mv minivmac minivmac-36.04-lx64-${{ matrix.model }}-960x600
           
      - name: uploading
        uses: actions/upload-artifact@v3
        with: 
          name: linux64-builds
          path: minivmac-36.04-*
  linux86:
    runs-on: ubuntu-latest
    steps:
      - name: enable i386 arch
        run: sudo dpkg --add-architecture i386 && sudo apt update && sudo apt install libx11-dev:i386
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
        # gcc-multilib
          packages: gcc-multilib-i686-linux-gnu xorg-dev libx11-dev:i386
          version: 1.1
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: 36.04
      #- name: Install 32-bit gcc
      #  run: sudo apt install -y gcc-i686-linux-gnu
      - name: configure dev options
        run: |
           mkdir -p downloads
           mkdir -p dep
           echo "#define kMaintainerName \"Jake Thomas\"" > setup/CONFIGUR.i
           echo "#define kStrHomePage \"https://github.com/jake01756/Mini-vMac\"" >> setup/CONFIGUR.i
           echo '#define cur_ide gbk_ide_mvc' >> setup/CONFIGUR.i
           more setup/CONFIGUR.i
           #sed -i 's/WriteCStrToDestFile("$(my_prefix)gcc -c");/WriteCStrToDestFile("$(my_prefix)g -c");/g' setup/WRMVCFLS.i
           sed -i 's/WriteDestFileLn("my_prefix = i386-pc-linux-");/WriteDestFileLn("my_prefix = i686-linux-gnu-");/g' setup/WRMVCFLS.i
           			

           more setup/WRMVCFLS.i
      - name: Cache Build Tool
        id: cache-build-linux-tool32
        uses: actions/cache@v3
        with:
          path: setup_t
          key: ${{ runner.os }}-setup_t-linux86
      - name: build setup tool
        if: steps.cache-build-linux-tool32.outputs.cache-hit != 'true'
        run: gcc setup/tool.c -o setup_t
      
      - name: build linux x86 mPlus
        run: |
           #
           # MAC PLUS BUILDS
           #
           
            #./setup_t -t lx86 -n "minivmac-36.04-lx86-mPlus-512x384" -maintainer "Jake Thomas" -homepage "github.com/jake01756/Mini-vMac" -m Plus -depth 0 -hres 512 -vres 384 -sound 1 -drives 12 > setup.sh
           ./setup_t -t lx86 -n "minivmac-36.04-lx86-mPlus-512x484" -m Plus -hres 512 -vres 384 -depth 0 -sound 1 -drives 12 > setup.sh
           . setup.sh && make
           mv minivmac minivmac-36.04-lx86-mPlus-512x384
           
           #./setup_t -t lx86 -n "minivmac-36.04-lx86-mPlus-640x400" -maintainer "Jake Thomas" -homepage "github.com/jake01756/Mini-vMac" -m Plus -depth 0 -hres 640 -vres 400 -sound 1 -drives 12 > setup.sh
           ./setup_t -t lx86 -n "minivmac-36.04-lx86-mPlus-640x400" -m Plus -hres 640 -vres 400 -depth 0 -sound 1 -drives 12 > setup.sh
           . setup.sh && make
           mv minivmac minivmac-36.04-lx86-mPlus-640x400
          
           #./setup_t -t lx86 -n "minivmac-36.04-lx86-mPlus-640x512" -maintainer "Jake Thomas" -homepage "github.com/jake01756/Mini-vMac" -m Plus -depth 0 -hres 640 -vres 512 -sound 1 -drives 12 > setup.sh
           ./setup_t -t lx86 -n "minivmac-36.04-lx86-mPlus-640x512" -m Plus -hres 640 -vres 512 -depth 0 -sound 1 -drives 12 > setup.sh
           . setup.sh && make
           mv minivmac minivmac-36.04-lx86-mPlus-640x512
           
           #./setup_t -t lx86 -n "minivmac-36.04-lx86-mPlus-704x450" -maintainer "Jake Thomas" -homepage "github.com/jake01756/Mini-vMac" -m Plus -depth 0 -hres 704 -vres 450 -sound 1 -drives 12 > setup.sh
           ./setup_t -t lx86 -n "minivmac-36.04-lx86-mPlus-704x450" -m Plus -hres 704 -vres 450 -depth 0 -sound 1 -drives 12 > setup.sh
           . setup.sh && make
           mv minivmac minivmac-36.04-lx86-mPlus-704x450
           
           #./setup_t -t lx86 -n "minivmac-36.04-lx86-mPlus-832x525" -maintainer "Jake Thomas" -homepage "github.com/jake01756/Mini-vMac" -m Plus -depth 0 -hres 832 -vres 525 -sound 1 -drives 12 > setup.sh
           ./setup_t -t lx86 -n "minivmac-36.04-lx86-mPlus-832x525" -m Plus -hres 832 -vres 525 -depth 0 -sound 1 -drives 12 > setup.sh
           . setup.sh && make
           mv minivmac minivmac-36.04-lx86-mPlus-832x525
           
           #./setup_t -t lx86 -n "minivmac-36.04-lx86-mPlus-960x540" -maintainer "Jake Thomas" -homepage "github.com/jake01756/Mini-vMac" -m Plus -depth 0 -hres 960 -vres 540 -sound 1 -drives 12 > setup.sh
           ./setup_t -t lx86 -n "minivmac-36.04-lx86-mPlus-960x540" -m Plus -hres 960 -vres 540 -depth 0 -sound 1 -drives 12 > setup.sh
           . setup.sh && make
           mv minivmac minivmac-36.04-lx86-mPlus-960x540
           
           #./setup_t -t lx86 -n "minivmac-36.04-lx86-mPlus-960x600" -maintainer "Jake Thomas" -homepage "github.com/jake01756/Mini-vMac" -m Plus -depth 0 -hres 960 -vres 600 -sound 1 -drives 12 > setup.sh
           ./setup_t -t lx86 -n "minivmac-36.04-lx86-mPlus-960x600" -m Plus -hres 960 -vres 600 -depth 0 -sound 1 -drives 12 > setup.sh
           . setup.sh && make
           mv minivmac minivmac-36.04-lx86-mPlus-960x600
           
      - name: uploading
        uses: actions/upload-artifact@v3
        with: 
          name: linux86-builds
          path: minivmac-36.04-*
 
    
  release_linux:
    needs: [linux64, linux86]
    #needs: [linux64, linux86, linuxppc, linuxarm]
    runs-on: ubuntu-latest
    steps:
      - name: Download Linux 64 Builds
        uses: actions/download-artifact@v3
        with:
          name: linux64-builds
          path: builds/linux/
      - name: Download Linux 86 Builds
        uses: actions/download-artifact@v3
        with:
          name: linux86-builds
          path: builds/linux/
      # - name: Download Linux PPC Builds
      #   uses: actions/download-artifact@v3
      #   with:
      #     name: linuxppc-builds
      #     path: builds/linux/
      # - name: Download Linux ARM Builds
      #   uses: actions/download-artifact@v3
      #   with:
      #     name: linuxarm-builds
      #     path: builds/linux/
      - name: Release
        uses: softprops/action-gh-release@v1
        #if: startsWith(github.ref, 'refs/tags/')
        with:
          name: "Latest 36.04 Linux Builds"
          body: "These are the linux builds that were compiled during the last push or merge."
          prerelease: true
          draft: false
          tag_name: "latest-linux"
          token: "${{ secrets.GITHUB_TOKEN }}"
          files: |
            builds/linux/*
