name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: install required packages 
        run: sudo apt install mingw-w64 gcc-mingw-w64-i686 clang
      - name: build setup tool
        run: gcc setup/tool.c -o setup_t
      - name: configure dev options
        run: |
           mkdir -p downloads
           echo "#define kMaintainerName \"Jake Thomas\"" > setup/CONFIGUR.i
           echo "#define kStrHomePage \"https://github.com/jake01756/Mini-vMac\"" >> setup/CONFIGUR.i
           echo "#define cur_ide gbk_ide_mgw" >> setup/CONFIGUR.i
      - name: build linux x64
        run: |
           #./setup_t -t lx64 -n "minivmac-36.04-lx64-mII" -maintainer "Jake Thomas" -homepage "github.com/jake01756/Mini-vMac" -m II -hres 640 -vres 512 -depth 5 -sound 1 -drives 12 -mem 8M > setup.sh
           ./setup_t -t lx64 -n "minivmac-36.04-lx64-mII" -m II -hres 640 -vres 512 -depth 5 -sound 1 -drives 12 -mem 8M > setup.sh
           . setup.sh
           make
           mv minivmac minivmac-36.04-lx64-mII
           mv minivmac-36.04-lx64-mII downloads/minivmac-36.04-lx64-mII
  windows:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: install required packages 
        run: sudo apt install mingw-w64 gcc-mingw-w64-i686 clang
      - name: build setup tool
        run: gcc setup/tool.c -o setup_t
      - name: configure dev options
        run: |
           mkdir -p downloads
           echo "#define kMaintainerName \"Jake Thomas\"" > setup/CONFIGUR.i
           echo "#define kStrHomePage \"https://github.com/jake01756/Mini-vMac\"" >> setup/CONFIGUR.i
           echo "#define cur_ide gbk_ide_mgw" >> setup/CONFIGUR.i
      - name: build win64
        run: |
           #./setup_t -t wx64 -n "minivmac-36.04-win64-mII" -maintainer "Jake Thomas" -homepage "github.com/jake01756/Mini-vMac" -m II -hres 640 -vres 512 -depth 5 -sound 1 -drives 12 -mem 8M > setup.sh
           ./setup_t -t wx64 -n "minivmac-36.04-win64-mII" -m II -hres 640 -vres 512 -depth 5 -sound 1 -drives 12 -mem 8M > setup.sh
           . setup.sh
           make
           cp minivmac minivmac-36.04-win64-mII
      - name: build win32
        run: |
           #./setup_t -t wx86 -n "minivmac-36.04-win86-mII" -maintainer "Jake Thomas" -homepage "github.com/jake01756/Mini-vMac" -m II -hres 640 -vres 512 -depth 5 -sound 1 -drives 12 -mem 8M > setup.sh
           ./setup_t -t wx86 -n "minivmac-36.04-win86-mII" -m II -hres 640 -vres 512 -depth 5 -sound 1 -drives 12 -mem 8M > setup.sh
           . setup.sh
           make
           cp minivmac minivmac-36.04-win86-mII

      - name: moving files
        run: |
          mv minivmac-36.04-win64-mII downloads/minivmac-36.04-win64-mII
  macos:
    runs-on: macos-10.15
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: build setup tool
        run: gcc setup/tool.c -o setup_t
      - name: configure dev options
        run: |
           mkdir -p downloads
           echo "#define kMaintainerName \"Jake Thomas\"" > setup/CONFIGUR.i
           echo "#define kStrHomePage \"https://github.com/jake01756/Mini-vMac\"" >> setup/CONFIGUR.i
           echo "#define cur_ide gbk_ide_mgw" >> setup/CONFIGUR.i
  release:
    runs-on: ubuntu-latest
    needs: [windows, linux, macos]
    steps:
      - name: uploading
        uses: actions/upload-artifact@v2
        with: 
          name: builds-x64
          path: downloads
      - name: Release
        uses: softprops/action-gh-release@v1
        #if: startsWith(github.ref, 'refs/tags/')
        with:
          name: "Latest Builds"
          body: "These are the builds that were compiled during the last `git push` or merge."
          prerelease: true
          draft: false
          token: "${{ secrets.GITHUB_TOKEN }}"
          files: |
            downloads/*.*
