name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build setup tool
      run: gcc setup/tool.c -o setup_t
    - name: build linux x64
    - run: |
         ./setup_t -t lx64 -n "minivmac-36.04-lx64-mII" maintainer "Jake Thomas" -homepage "github.com/jake01756/Mini-vMac" -m II -hres 640 -vres 512 -depth 5 -sound 1 -drives 12 -mem 8M > setup.sh
         . setup.sh
         make
    - name: build linux x86
      run: |
         ./setup_t -t lx86 -n "minivmac-36.04-lx86-mII" maintainer "Jake Thomas" -homepage "github.com/jake01756/Mini-vMac" -m II -hres 640 -vres 512 -depth 5 -sound 1 -drives 12 -mem 8M > setup.sh
         . setup.sh
         make
    upload:
    - uses: actions/upload-artifact@v2
      runs-on: ubuntu-latest
      with:
         name: Linux x64
         path: minivmac-36.04-lx64-mII
