name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build setup tool
      run: |
         gcc setup/tool.c -o setup_t
         ./setup_t -t lx64 > setup.sh
         
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
